# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [ ]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [17]:
import numpy as np
A = np.arange(1, 16).reshape(3,5)

print(A)

print("Dimension", A.ndim)
print("Shape", A.shape)
print("Size", A.size)
print("Datatype", A.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Dimension 2
Shape (3, 5)
Size 15
Datatype int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [45]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)
print()

#Elementwise subtraction
D = B - C
print("Elementwise subtraction")
print(D)
print()

#Elementwise multiplication
E = B * C
print("Elementwise multiplikation")
print(E)
print()

#Matrix multiplication
F = B @ C
print("Matrix multiplication")
print(F)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

Elementwise subtraction
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise multiplikation
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix multiplication
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [77]:
B = np.arange(1, 10).reshape(3, 3)
print(B)
print()

# Exponentiate each number elementwise
C = np.exp(B)
print("Exponentiate each element in the array")
print(C)
print()

# Calculate the minimum value in the whole matrix
D = np.min(B)
print("Minimum value in the whole matrix")
print(D)
print()

#Calculcate the minimum value in each row
E = B.min(axis=1)
print("Minimum value in each row")
print(E)
print()

#Calculcate the minimum value in each column
F = B.min(axis=0)
print("Minimum value in each column")
print(F)
print()

#Find the index value for the minimum value in the whole matrix
G = np.argmin(B)
print("Index value for the minimum value in the whole matrix")
print(G)
print()

#Find the index value for the minimum value in each row
H = np.argmin(B, axis=1)
print("Index value for the minimum value in each row")
print(H)
print()

#Calculate the sum for all elements
I = np.sum(B)
print("Sum for all elements")
print(I)
print()

#Calculate the mean for each column
J = np.mean(B, axis=0)
print("Mean for each column")
print(J)
print()

#Calculate the median for each column
K = np.median(B, axis=0)
print("Median for each column")
print(K)


[[1 2 3]
 [4 5 6]
 [7 8 9]]

Exponentiate each element in the array
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value in the whole matrix
1

Minimum value in each row
[1 4 7]

Minimum value in each column
[1 2 3]

Index value for the minimum value in the whole matrix
0

Index value for the minimum value in each row
[0 0 0]

Sum for all elements
45

Mean for each column
[4. 5. 6.]

Median for each column
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [ ]:
print(A)

In [ ]:
A[1]

**Answer:**

In [ ]:
When we provide fewer indices than axes when slicing a NumPy array, it means that we are selecting all elements along the unspecified axes.
In our example A[1] means that the expression within brackets in A[1] is treated as an 1 followed by as many instances of : as needed to 
represent the remaining axes.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [ ]:
A

In [ ]:
for i in A:
    print(i)

In [ ]:
#Answer: If we want to perform an operation on each element in the array, we can use the flat attribute which is an iterator over all the elements of the array.

for element in A.flat:
    print(element)

### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [79]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
#Answer: 
a = np.arange(30)          # this code will create a 1D array containing integers from 0 - 29
b = a.reshape((2, 3, -1))  # this will reshape the array a as 2 blocks with 3 rows.
                           #-1 indicates that NumPy can "do" an automatic operation and choose the number of columns as needed.
                            
print(a)
print()

print(b)

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [ ]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [ ]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

In [ ]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [87]:
import numpy as np

def add_mult_matrices(input1, input2, method):
    #Validation if the inputs are the type numpy.ndarray
    if not isinstance(input1, np.ndarray) or not isinstance(input2, np.ndarray):
        raise TypeError("Only matrices are allowed as inputs")
        
    #Validation if method is add or multiply
    if method not in ['add', 'multiply']:
        raise ValueError("The method can be either 'add' or 'multiply'")

    #Performing addition of the inputs
    if method == 'add':
        #Validation if matrix inputs have the same shape
        if input1.shape != input2.shape:
            raise ValueError("Matrices must have the same shape for addition")
            #Returning the result of addition
        return np.add(input1, input2)

    #Performing multiplication of the inputs
    elif method == 'multiply':
        #Validation if number of columns in first matrix is same as the number of rows in the second matrix
        if input1.shape[1] != input2.shape[0]:
            raise ValueError('Number of columns in matrix 1 must be same as number of rows in matrix 2')
            #Returning the result of multiplication
        return np.dot(input1, input2)

#Test 
input1 = np.array([[1, 2, 3], [4, 5, 6]])
input2 = np.array([[7, 8, 9], [10, 11, 12]])
method = 'add'

result = add_mult_matrices(input1, input2, method)
print("Result: ")
print(result)

Result: 
[[ 8 10 12]
 [14 16 18]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [121]:
# Uppgift 10.1.1

# Definiera vektor x
x = np.array([4, 3])
print("Vektor x:", x)

#Dimension på vektor x
print("Dimension på vektor x:", x.shape)

#Beräkna 5x
print("5x:", (5 * x))

#Beräkna 3x
print("3x:", (3 * x))

#Beräkna 5x + 3x
print("5x + 3x:", 5 * x  + 3 * x)

#Beräkna 8x
print("8x:", (8 * x))

#Beräkna 4x -x
print("4x - x:", 4 * x - x)

#Beräkna x transponat
print("x transponat:", x.T)
print("Den nya dimension efter transponeringen:", x.T.shape)

# Är x + x transponat definierat?
print("x + x.T:", x + x.T)  # NumPy räknar ut detta men egentligen är det ej definierat.

#Beräkna ||x||
norm_x = np.sqrt(np.sum(x**2))
print("Normen av vektor x:", norm_x)

Vektor x: [4 3]
Dimension på vektor x: (2,)
5x: [20 15]
3x: [12  9]
5x + 3x: [32 24]
8x: [32 24]
4x - x: [12  9]
x transponat: [4 3]
Den nya dimension efter transponeringen: (2,)
x + x.T: [8 6]
Normen av vektor x: 5.0


In [147]:
# Uppgift 10.1.2

#Definiera vektor v
v = np.array([[3], [7], [0], [11]])
print("Vektor v:")
print(v)

#Dimension på vektor v
print("Dimension på vektor v:", v.shape)
print()

#Beräkna 2v
print("2v:")
print(2 * v)
print()

#Beräkna 5v
print("5v:")
print(5 * v)
print()

#Beräkna 5v + 2v
print("5v + 2v:")
print(5 * v  + 2 * v)
print()

#Beräkna 4v -2v
print("4v - 2v:")
print(4 * v - 2 * v)
print()

#Beräkna v transponat
print("v transponat:", v.T)
print("Den nya dimension efter transponeringen:", v.T.shape)
print()

#Beräkna ||v||
norm_v = np.sqrt(np.sum(v**2))
print("Normen av vektor v:", norm_v)

Vektor v:
[[ 3]
 [ 7]
 [ 0]
 [11]]
Dimension på vektor v: (4, 1)

2v:
[[ 6]
 [14]
 [ 0]
 [22]]

5v:
[[15]
 [35]
 [ 0]
 [55]]

5v + 2v:
[[21]
 [49]
 [ 0]
 [77]]

4v - 2v:
[[ 6]
 [14]
 [ 0]
 [22]]

v transponat: [[ 3  7  0 11]]
Den nya dimension efter transponeringen: (1, 4)

Normen av vektor v: 13.379088160259652


In [153]:
#Uppgift 10.1.3
#Definiera vektorerna v1 och v2
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])
print("Vektor v1:", v1)
print("Vektor v2:", v2)

#Beräkna ||v1||
norm_v1 = np.sqrt(np.sum(v1**2))
print("Normen av vektor v1:", norm_v1)

#Beräkna ||v1 - v2||
norm_v2 = np.sqrt(np.sum(v2**2))
print("Normen av vektor v1 - v2:", norm_v1 - norm_v2)

Vektor v1: [4 3 1 5]
Vektor v2: [2 3 1 1]
Normen av vektor v1: 7.14142842854285
Normen av vektor v1 - v2: 3.2684450823354334


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [199]:
#Uppgift 10.2.1
#Definiera matriserna

A = np.array([[2, 1, -1],
              [1, -1, 1]])

B = np.array([[4, -2, 1],
              [2, -4, -2]])

C = np.array([[1, 2],
              [2, 1]])

D = np.array([[3, 4],
              [4, 3]]) 

E = np.array([[1],
              [2]]) 

I = np.array([[1, 0],
              [0, 1]]) 

#Beräkna 2A
print("2A:")
print(2 * A)
print()

#Beräkna B - 2A
print("B - 2A:")
print(B - 2 * A)
print()

#Beräkna 3C - 2E
print("3C - 2E:")
print(3 * C - 2 * E)   # NumPy räknar ut detta fast det är ej definierat.
print()

#Beräkna 2D - 3C
print("2D - 3C:")
print(2 * D - 3 * C) 
print()

#Beräkna D.T (D transponat) + 2D
print("D.T + 2D:")
print(D.T + 2 * D)
print()

#Beräkna 2C.T - 2D.T
print("2C.T - 2D.T:")
print(2 * C.T - 2 * D.T)
print()

#Beräkna A.T - B     Fick error när jag försökte köra detta
#print("A.T - B:")
#print(A.T - B)
#print("Ej definierat!")
#print()

#Beräkna AC         Fick error när jag försökte köra detta
#print("AC:")
#print(A * C)
#print("Ej definierat!")
#print()

#Beräkna CD  
CD = C @ D
print("CD:")
print(CD)
print()

#Beräkna CB  
CB = C @ B
print("CB:")
print(CB)
print() 

#Beräkna CI  
CI = C @ I
print("CI:")
print(CI)
print() 

#Beräkna AB.T
print("AB.T:")
print(A @ B.T)
print()

2A:
[[ 4  2 -2]
 [ 2 -2  2]]

B - 2A:
[[ 0 -4  3]
 [ 0 -2 -4]]

3C - 2E:
[[ 1  4]
 [ 2 -1]]

2D - 3C:
[[3 2]
 [2 3]]

D.T + 2D:
[[ 9 12]
 [12  9]]

2C.T - 2D.T:
[[-4 -4]
 [-4 -4]]

CD:
[[11 10]
 [10 11]]

CB:
[[  8 -10  -3]
 [ 10  -8   0]]

CI:
[[1 2]
 [2 1]]

AB.T:
[[5 2]
 [7 4]]



In [201]:
#Uppgift 10.2.2

#Definiera matrisen
A = np.array([[2, 3, 4],
              [5, 4, 1]])

#Beräkna AA.T
print("AA.T:")
print(A @ A.T)
print()

AA.T:
[[29 26]
 [26 42]]



In [203]:
#Uppgift 10.2.3

#Definiera matrisen
A = np.array([[1, 2],
              [2, 4]]) 

B = np.array([[2, 1],
              [1, 3]]) 

C = np.array([[4, 3],
              [0, 2]])

#Verifiera att AB = AC men att B är inte lika med C

#Beräkna AB  
AB = A @ B
print("AB:")
print(AB)
print() 

#Beräkna AC  
AC = A @ C
print("AC:")
print(AC)
print() 

AB:
[[ 4  7]
 [ 8 14]]

AC:
[[ 4  7]
 [ 8 14]]



### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [ ]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

In [ ]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

In [ ]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

Det verkar som du har svarat på frågorna själv.
// Tahira